modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="sophisticated_advanced_crafting.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sophisticatedcore"
    type="required"
    versionRange="[1.5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sophisticatedbackpacks"
    type="optional"
    versionRange="[3.24,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sophisticatedstorage"
    type="optional"
    versionRange="[1.4,)"
    ordering="NONE"
    side="BOTH"
